version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
  discard-paths: yes
