# This is a basic workflow that is manually triggered

name: Manual Deploy to S3 Bucket

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job will build and deploy static website to aws s3 bucket
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Runs commands using the runners shell
      - name: Install Dependencies
        run: |
          node --version
          npm ci --production

      # Build static web site
      - name: Build Angular Application
        run: npm run build
